name: agenda_isapre
description: "Listado de tareas para usuarios"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: 5.4.1
  mobx: ^2.3.0+1
  flutter_mobx: ^2.2.0+2
  get_it: ^7.6.7
  provider: ^6.0.4
  flutter_slidable: ^3.1.0
  flutter_localizations:
    sdk: flutter
  intl: any
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  device_info_plus: ^3.2.3
  flutter_screenutil: ^5.9.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  mobx_codegen: ^2.6.0+1
  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true
